### ISSUE TITLE
Multiple filestack forms causes it to not submit and save

### ISSUE THREAD

**Issue by masudhossain** [filestack/filestack-rails#182]
I've noticed that if i have multiple forms in the page. 

ie. 1 form to create a new post and another to update previous posts, it won't work.

Is this a known problem?

**Comment by masudhossain** [comment]
http://prntscr.com/iimkda

**Comment by masudhossain** [comment]
Are you guys planning on doing a fix for this? This problem is effecting the user experience of my software.

**Comment by masudhossain** [comment]
Extremely disappointed on how this repo is managed.

**Comment by gabifiolek** [comment]
@masondesu I took a look on your code, and I reproduced your issue in my test rails app.
Instead of using `id: 'unique-id'`, you should write `input_id: 'unique-id'`. 

Could you please use `filestack_field` as follow:
`<%= f.filestack_field :image_url , 'Upload', input_id: 'unique-id', required: true %>`

Let me know if that helps.

**Comment by masondesu** [comment]
@gabifiolek I'm guessing you meant to tag @masudhossain instead of me :)

**Comment by gabifiolek** [comment]
@masondesu hahaha, yes! :) thank you for quick response!
cc @masudhossain 
and also here is a source code: https://github.com/filestack/filestack-rails/blob/a66c79224afafe1f9e67840f807635b824f7d23f/app/helpers/filestack_rails/form_helper.rb#L13 ;)
