### ISSUE TITLE
Doesn't work out of the box with turbolinks

### ISSUE THREAD

**Issue by mattbrictson** [filestack/filestack-rails#52]
The filepicker JavaScript seems to rely on the window load event to initialize itself. With Rails turbolinks (enabled by default in Rails 4), there is no longer a guarantee that this load event will fire after a page navigation. So in many cases after navigating the filepicker widgets do not work.

I suppose using [jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks) could work around this issue.

Is there a better solution?

**Comment by goldnuggets24** [comment]
I'm not sure if this is related, but my build (using turbolinks, rails 4), the 'onPhotoUpload' event is not being recognized. I am loading the API js in my body as suggested, and the upload button is loading fine. However, I would LOVE to be able to load and view the photos on upload. Are there any solutions? 

My apologies if this question needs to be moved from this discussion. Thank you everyone for your help and for such a great product.

**Comment by maurogeorge** [comment]
@goldnuggets24 you can search on this thread for some solutions, until today I think we do not have a final solution to fix this, since this is related to the Filepicker JS.

If we have a good solution to this we can try add this to the gem. Today the gem only include the default filepicker JavaScript.

**Comment by goldnuggets24** [comment]
@maurogeorge thank you! I'll keep looking around and will post if I find a solution.

**Comment by travisp** [comment]
This problem is more challenging when you're using the javascript API alone instead of the input widgets (running constructWidget is not a solution here, nor is putting the filepicker javascript tag in the body). It seems that I can get filepicker to reload the iframes by setting window.filepicker to null before loading the filepicker script, but it would be helpful if filepicker could include a public method for resetting and regenerating the iframes.

**Comment by jlerpscher** [comment]
Any news on this? Today, what is the best way to use FilePicker's gem? 

We are currently working with jquery-turbolinks gem but FilePicker button disappear on page refresh or on failed form submission.

**Comment by ybart** [comment]
:+1:

**Comment by staturecrane** [comment]
We are currently in the process of revamping the Gem to use our new File Picker and image transformations. I will address this issue before release and ensure it is not a problem before publishing the new version.
