### ISSUE TITLE
Add option to show initial thumbnail, update on change, and allow removing it

### ISSUE THREAD

**Issue by danmichaelson** [filestack/filestack-rails#87]
Since this gem aims to provide an image upload form field for your Rails object, given the name of the record's image attribute: it seems like it would be good to go the whole way and provide the rest of the functionality that most forms would need, so that I don't have to roll my own onchange code. Show a thumbnail for the initial value of the image_url field (or whatever you want to call it); update the thumbnail when the user uploads a new image; and allow removing an existing image.

**Comment by carlosramireziii** [comment]
@danmichaelson While your solution may not be generalized enough to warrant a code contribution, perhaps you could still share it in the form of a Wiki entry outlining what you do so that others can adapt it to their own situation. Like you said most forms are going to need functionality to display an image thumbnail and then update it using the `onchange` event, and it'd be great to see an example of that. 

Would you mind adding your implementation to the Wiki?
